customer:
    datasource:
        host: localhost
        database: dbSRC
        port: 3306
        username: user
        password: password

# start dummy stuff so JPA doesn't cry
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dbSRC
        username: user
        password: password
    jpa:
        hibernate:
            ddl-auto: update
# end dummy stuff so JPA doesn't cry

## Logging properties
logging:
    file: 
        name: logs/debezium.log
